import {
  AcademicCapIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowsRightLeftIcon,
  BanknotesIcon,
  BeakerIcon,
  BoltIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingLibraryIcon,
  BuildingOfficeIcon,
  BuildingStorefrontIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  CameraIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  ComputerDesktopIcon,
  CreditCardIcon,
  CurrencyDollarIcon,
  DevicePhoneMobileIcon,
  DocumentTextIcon,
  FaceSmileIcon,
  FilmIcon,
  FireIcon,
  GlobeAltIcon,
  GiftTopIcon,
  HeartIcon,
  HomeIcon,
  HomeModernIcon,
  KeyIcon,
  LifebuoyIcon,
  LightBulbIcon,
  MapPinIcon,
  MusicalNoteIcon,
  NewspaperIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PhoneIcon,
  PhotoIcon,
  PresentationChartLineIcon,
  PuzzlePieceIcon,
  QuestionMarkCircleIcon,
  ReceiptPercentIcon,
  ScaleIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SparklesIcon,
  TagIcon,
  TicketIcon,
  TrophyIcon,
  TruckIcon,
  TvIcon,
  UserGroupIcon,
  WalletIcon,
  WifiIcon,
  WrenchIcon,
  WrenchScrewdriverIcon
} from '@heroicons/vue/24/solid';

export const CATEGORY_ICON_OPTIONS = [
  { value: 'home', label: 'Home', component: HomeIcon },
  { value: 'home-modern', label: 'Rent', component: HomeModernIcon },
  { value: 'shopping-bag', label: 'Shopping bag', component: ShoppingBagIcon },
  { value: 'shopping-cart', label: 'Shopping cart', component: ShoppingCartIcon },
  { value: 'building-storefront', label: 'Groceries', component: BuildingStorefrontIcon },
  { value: 'truck', label: 'Transportation', component: TruckIcon },
  { value: 'paper-airplane', label: 'Travel', component: PaperAirplaneIcon },
  { value: 'map-pin', label: 'Local travel', component: MapPinIcon },
  { value: 'sparkles', label: 'Entertainment', component: SparklesIcon },
  { value: 'film', label: 'Movies', component: FilmIcon },
  { value: 'ticket', label: 'Events', component: TicketIcon },
  { value: 'tv', label: 'Streaming', component: TvIcon },
  { value: 'musical-note', label: 'Music', component: MusicalNoteIcon },
  { value: 'puzzle-piece', label: 'Hobbies', component: PuzzlePieceIcon },
  { value: 'face-smile', label: 'Fun', component: FaceSmileIcon },
  { value: 'heart', label: 'Health', component: HeartIcon },
  { value: 'lifebuoy', label: 'Insurance', component: LifebuoyIcon },
  { value: 'beaker', label: 'Medicine', component: BeakerIcon },
  { value: 'wallet', label: 'Savings', component: WalletIcon },
  { value: 'banknotes', label: 'Salary', component: BanknotesIcon },
  { value: 'currency-dollar', label: 'Cash', component: CurrencyDollarIcon },
  { value: 'arrow-trending-up', label: 'Investments', component: ArrowTrendingUpIcon },
  { value: 'arrow-trending-down', label: 'Fees', component: ArrowTrendingDownIcon },
  { value: 'arrows-right-left', label: 'Transfer', component: ArrowsRightLeftIcon },
  { value: 'briefcase', label: 'Business', component: BriefcaseIcon },
  { value: 'building-office', label: 'Office', component: BuildingOfficeIcon },
  { value: 'gift', label: 'Gifts', component: GiftTopIcon },
  { value: 'credit-card', label: 'Credit', component: CreditCardIcon },
  { value: 'receipt-percent', label: 'Bills', component: ReceiptPercentIcon },
  { value: 'calculator', label: 'Taxes', component: CalculatorIcon },
  { value: 'academic-cap', label: 'Education', component: AcademicCapIcon },
  { value: 'book-open', label: 'Books', component: BookOpenIcon },
  { value: 'presentation-chart-line', label: 'Analytics', component: PresentationChartLineIcon },
  { value: 'chart-bar', label: 'Reports', component: ChartBarIcon },
  { value: 'user-group', label: 'Family', component: UserGroupIcon },
  { value: 'building-library', label: 'Loans', component: BuildingLibraryIcon },
  { value: 'scale', label: 'Legal', component: ScaleIcon },
  { value: 'shield-check', label: 'Security', component: ShieldCheckIcon },
  { value: 'wrench-screwdriver', label: 'Maintenance', component: WrenchScrewdriverIcon },
  { value: 'wrench', label: 'Repairs', component: WrenchIcon },
  { value: 'bolt', label: 'Utilities', component: BoltIcon },
  { value: 'wifi', label: 'Internet', component: WifiIcon },
  { value: 'phone', label: 'Phone', component: PhoneIcon },
  { value: 'device-phone-mobile', label: 'Mobile', component: DevicePhoneMobileIcon },
  { value: 'computer-desktop', label: 'Computer', component: ComputerDesktopIcon },
  { value: 'camera', label: 'Camera', component: CameraIcon },
  { value: 'photo', label: 'Photos', component: PhotoIcon },
  { value: 'paint-brush', label: 'Creative', component: PaintBrushIcon },
  { value: 'newspaper', label: 'News', component: NewspaperIcon },
  { value: 'document-text', label: 'Documents', component: DocumentTextIcon },
  { value: 'calendar-days', label: 'Subscriptions', component: CalendarDaysIcon },
  { value: 'cake', label: 'Celebrations', component: CakeIcon },
  { value: 'light-bulb', label: 'Ideas', component: LightBulbIcon },
  { value: 'globe-alt', label: 'Online', component: GlobeAltIcon },
  { value: 'chat-bubble-left-right', label: 'Communication', component: ChatBubbleLeftRightIcon },
  { value: 'key', label: 'Access', component: KeyIcon },
  { value: 'tag', label: 'Deals', component: TagIcon },
  { value: 'trophy', label: 'Rewards', component: TrophyIcon },
  { value: 'fire', label: 'Urgent', component: FireIcon },
  { value: 'question-mark-circle', label: 'Other', component: QuestionMarkCircleIcon }
];

const CATEGORY_ICON_MAP = CATEGORY_ICON_OPTIONS.reduce((map, option) => {
  map[option.value] = option.component;
  return map;
}, {});

export function resolveCategoryIcon(name) {
  return CATEGORY_ICON_MAP[name] ?? null;
}

export const FALLBACK_CATEGORY_ICON = WalletIcon;
